CREATE OR REPLACE FUNCTION CalculateAge(p_dob DATE) RETURN NUMBER IS BEGIN RETURN FLOOR(MONTHS_BETWEEN(SYSDATE,p_dob)/12); END;/

CREATE OR REPLACE FUNCTION CalculateMonthlyInstallment(p_amt NUMBER,p_rate NUMBER,p_years NUMBER) RETURN NUMBER IS r NUMBER; n NUMBER; BEGIN r:=p_rate/(12*100); n:=p_years*12; RETURN (p_amt*r*POWER(1+r,n))/(POWER(1+r,n)-1); END;/

CREATE OR REPLACE FUNCTION HasSufficientBalance(p_acc NUMBER,p_amt NUMBER) RETURN BOOLEAN IS b NUMBER; BEGIN SELECT Balance INTO b FROM Accounts WHERE AccountID=p_acc; RETURN b>=p_amt; END;/